export const SET_LANGUAGE = 'SET_LANGUAGE';
export const UPDATE_KEYPAIR = 'UPDATE_KEYPAIR';
export const SHOW_SPINNER = 'SHOW_SPINNER';
export const SHOW_KEY_GENERATOR = 'SHOW_KEY_GENERATOR';
export const SHOW_GENERATOR_CONFIRM = 'SHOW_GENERATOR_CONFIRM';
export const SHOW_RECORD_SEED = 'SHOW_RECORD_SEED';
export const SHOW_COPY_COMPLETE = 'SHOW_COPY_COMPLETE';
export const SHOW_TRANSACTION_CONFIRM = 'SHOW_TRANSACTION_CONFIRM';
export const SHOW_TRANSACTION_COMPLETE = 'SHOW_TRANSACTION_COMPLETE';

export const STREAM_ACCOUNT = 'STREAM_ACCOUNT';
export const STREAM_EFFECTS = 'STREAM_EFFECTS';
export const STREAM_OFFERS = 'STREAM_OFFERS';
export const STREAM_PAYMENT = 'STREAM_PAYMENT';
export const RESET_HISTORY = 'RESET_HISTORY';

export const SET_MAINTENANCE = 'SET_MAINTENANCE';