export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SHOW_SPINNER = 'SHOW_SPINNER';
export const SHOW_KEY_GENERATOR = 'SHOW_KEY_GENERATOR';
export const SHOW_GENERATOR_CONFIRM = 'SHOW_GENERATOR_CONFIRM';